spring:
  config:
    activate:
      on-profile: local
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update

security:
  cookie:
    refresh:
      secure: false
      same-site: Lax
